export const FORFAITS: MockForfaits[] = [
    {
        destination: 'Riviera Maya, Mexique',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Ocean Riviera Paradise',
            adresse: 'Cancún Km. 296 Predio Montecarlos Lotes 7 Predio Punta Bete Lote 15-5 CP77710 Playa Del Carmen Quintana Roo, Mexique',
            nombreEtoiles: 5,
            nombreChambres: 350,
            photo: "https://wcm.transat.com/getmedia/0c380422-7977-4597-aae0-d62131e253a8/OceanRivieraParadise-Aerial-001-AR.aspx",
            caracteristiques: [ 'Face à la plage',
                                "Proximité d'un lieu naturel",
                                "Ascenseur",
                                "Miniclub",
                                "Réalisation de mariages", 
                                '10 restaurants',
                                'WiFi: tout le complex', 
                                'Parque aquiatique'],
        },
        dateDepart: '15/11/2020',
        dateRetour: '22/11/2020',
        prix: 1150,
        rabais: 100,
        forfaitVedette: true
    },
    {
        destination: 'Holguin, Cuba',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Playa Costa Verde',
            adresse: 'Playa Pesquero, Rafael Freye Holguin, 82200 Cuba',
            nombreEtoiles: 3,
            nombreChambres: 480,
            photo: "https://media-cdn.tripadvisor.com/media/photo-s/13/04/c9/48/hotel-playa-costa-verde.jpg",
            caracteristiques: [ 'Tout inclus', 
                                'Miniclub ',
                                "2 piscines",
                                "5 restaurants",
                                "7 bars",
                                "Wi-Fi ($) : hall", 
                                'Collations 24 h',
                                "Salle d'exercice", 
                                'Mariages '],
        },
        dateDepart: '13/12/2020',
        dateRetour: '21/12/2020',
        prix: 979,
        rabais: 0,
        forfaitVedette: false
    },
    {
        destination: 'Punta Cana, République dominicaine',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Ocean Blue & Sand',
            adresse: 'Arena Gorda sn. Playa Bavaro, République dominicaine',
            nombreEtoiles: 5,
            nombreChambres: 708,
            photo: "https://images.sunwingtravelgroup.com/HotelImages/PUJOBA/16x9/032.jpg",
            caracteristiques: [ 'Tout inclus', 
                                'Miniclub ',
                                "2 piscines",
                                "10 restaurants",
                                "7 bars",
                                "Wi-Fi : dans tout le complexe", 
                                'Collations 24 h',
                                "Plage", 
                                'Mariages '],
        },
        dateDepart: '18/12/2020',
        dateRetour: '25/12/2020',
        prix: 1009,
        rabais: 50,
        forfaitVedette: false
    },
    {
        destination: 'San Juan, Porto Rico',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Verdanza',
            adresse: '8020 Tartak, Isla Verde, Puerto Rico 00979',
            nombreEtoiles: 4,
            nombreChambres: 222,
            photo: "https://ssl.tzoo-img.com/images/tzoo.hd.76148.6699.486772.VerdanzaHotel.jpg?width=1080" ,
            caracteristiques: [ 'Au cœur de la zone hôtelière', 
                                'Wi-Fi : hall',
                                "Piscine",
                                "2 restaurants",
                                "7 bars",
                                "De l’autre côté de la rue longeant la plage", 
                                'Collations 24 h',
                                "Salle d'exercice", 
                                'Coffret de sûreté'],
        },
        dateDepart: '18/12/2020',
        dateRetour: '25/12/2020',
        prix: 1209,
        rabais: 149,
        forfaitVedette: false
    },
    {
        destination: 'Puerto Vallarta, Mexique',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Friendly Vallarta',
            adresse: 'Ave. Francisco Medina Ascencio Km 2.5, Zona Hetelera 483330 Puerto Vallarta, Jalisco Mexique',
            nombreEtoiles: 4,
            nombreChambres: 270,
            photo: "https://www.westjet.com/assets/wj-web/images/hotels/pvr/pvrhol-friendly-vallarta-formally-known-as-the-hola-puerto-vallarta/overview/friendly-vallarta_overview.jpg",
            caracteristiques: [ 'Face à la plage', 
                                'Wi-Fi : hall',
                                "3 piscines",
                                "5 restaurants",
                                "Spa ($)",
                                "1 édifice de 14 étages", 
                                'Ascenseur',
                                "Salle d'exercice", 
                                "Près d'un lieu culturel"],
        },
        dateDepart: '11/01/2021',
        dateRetour: '18/01/2021',
        prix: 1379,
        rabais: 250,
        forfaitVedette: true
    },
    {
        destination: 'Montego Bay, Jamaïque',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Royal Decameron',
            adresse: '2 Gloucester Avenue Montego Bay Jamaïque',
            nombreEtoiles: 4,
            nombreChambres: 144,
            photo: "https://cf.bstatic.com/images/hotel/max1280x900/112/112587274.jpg",
            caracteristiques: [ 'Face à la plage', 
                                'Wi-Fi : hall',
                                "Près d'un attrait/ville/lieu historique",
                                "2 restaurants",
                                "2 piscines",
                                "4 bars",
                                "Salle d'exercice",
                                "Coffret de sûreté ($)", 
                                'Ascenseur',
                                "Salle d'exercice", 
                                "Mariages"],
        },
        dateDepart: '01/04/2021',
        dateRetour: '08/04/2021',
        prix: 1479,
        rabais: 300,
        forfaitVedette: true
    },
];
